### ISSUE TITLE
19.3 Beta Cinnamon - no video thumbnailer installed by default.

### ISSUE THREAD

**Issue by smurphos** [linuxmint/mint19.3-beta#1]
Hi,

With xplayer gone as a default app along with xplayer-video-thumbnailer, there is no video thumbnailer installed out of the box. 

Easily worked around with `apt install ffmpegthumbnailer` for those in the know, but it would be nice if this was preinstalled for the stable release.

**Comment by clefebvre** [comment]
Ah no, I was sure I added that as a dependency to celluloid... damn :)

**Comment by clefebvre** [comment]
I added it as a build-dep instead of a dep, fixed in the next update.
