### ISSUE TITLE
mintupdate: KernelWindow, Polish translation shows some funny signs.

### ISSUE THREAD

**Issue by MichalKolesinski** [linuxmint/mint19.3-beta#10]
![kernels](https://user-images.githubusercontent.com/39199872/70135549-8de34080-168a-11ea-8f00-9710e39fe7c6.png)
![kernelss](https://user-images.githubusercontent.com/39199872/70135559-92a7f480-168a-11ea-9d81-14c312d3c1fe.png)

**Comment by clefebvre** [comment]
Fixed in Launchpad, and added this character to the list of forbidden chars in the translation checker. Will be fixed in tricia as soon as we update the translations (there's a bug for this in trello).

**Comment by gm10** [comment]
@clefebvre for what it's worth, this displays perfectly fine in my fork despite the same characters in my .po. You didn't want my fix for Mint's version in times long past. SCNR. ;)

**Comment by clefebvre** [comment]
ah, I had to look up SCNR. Anyway, touche :)
