### ISSUE TITLE
Mint-X Icon for 'Disks' in System Settings seems odd

### ISSUE THREAD

**Issue by Acheron17** [linuxmint/mint19.3-beta#12]
This is solid repeatable.

Open the System Settings and scroll down to the new item "Disks".
As shown in the screen shots, Mint-X has the red stop circle and then when you switch to the Mint-Y icons, it shows a hard drive icon.

![Screenshot-from-2019-12-04-07-48-47](https://user-images.githubusercontent.com/45599505/70144216-72b50880-166b-11ea-9077-ad1e0135b66b.png)
![Screenshot-from-2019-12-04-07-49-34](https://user-images.githubusercontent.com/45599505/70144230-78aae980-166b-11ea-8c01-9b810aba8618.png)

**Comment by xenopeek** [comment]
Same issue as #4, which is fixed by https://github.com/linuxmint/cinnamon/commit/40a33842f2d820c11657bcb3a610601abe77a8ec.
