### ISSUE TITLE
Bookmarks reversed in Places section of Cinnamon menu

### ISSUE THREAD

**Issue by ghost** [linuxmint/mint19.3-beta#13]
Running the 19.3 Beta of Linux Mint Cinnamon, and the order of the bookmarks etc. is reversed in the Places section of the Menu (see attachment). They are in the correct order in Nemo, and I have not added to or altered them.
![Places](https://user-images.githubusercontent.com/40184535/70258696-9029c580-1784-11ea-9d24-9db560a2cfbc.png)

**Comment by xenopeek** [comment]
I can confirm that.

Editing the file **/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js** on my system and on [line 2119](https://github.com/linuxmint/cinnamon/blob/master/files/usr/share/cinnamon/applets/menu%40cinnamon.org/applet.js#L2119) replacing:
`this.applicationsBox.insert_child_below(button.actor, sibling);`
with
`this.applicationsBox.insert_child_above(button.actor, sibling);`
and then restarting Cinnamon fixes the issue.

Looking at the code around [line 2119](https://github.com/linuxmint/cinnamon/blob/master/files/usr/share/cinnamon/applets/menu%40cinnamon.org/applet.js#L2119), is the **Util.each(Main.placesManager.getAllPlaces() …** loop passing the places in reverse order?
