### ISSUE TITLE
linuxmint.com inaccessible from Greece

### ISSUE THREAD

**Issue by jtsagata** [linuxmint/mint19.3-beta#18]
Hello, i report here, as i have no other means to report it.

The last 24 hours linuxmint.com and forum is inaccessible from seems all Greek ISPs. You get an 403 error. Here is a trace route

```
traceroute linuxmint.com
traceroute to linuxmint.com (192.124.249.9), 64 hops max
  1   192.168.1.1  0,738ms  0,380ms  0,604ms 
  2   *  *  * 
  3   62.38.40.XX  32,958ms  33,851ms  33,703ms 
  4   62.38.37.86  34,717ms  33,845ms  33,986ms 
  5   62.38.97.150  33,721ms  34,104ms  33,694ms 
  6   62.38.93.221  33,970ms  34,325ms  33,971ms 
  7   195.89.103.69  35,189ms  33,391ms  36,422ms 
  8   195.2.2.70  36,688ms  34,322ms  33,853ms 
  9   195.2.21.57  45,307ms  45,533ms  46,013ms 
 10   195.2.14.166  65,448ms  47,421ms  47,480ms 
 11   213.254.230.57  46,483ms  45,640ms  46,014ms 
 12   *  *  * 
```

And if you try to connect to forums.linuxmint.com you get

![εικόνα](https://user-images.githubusercontent.com/159514/70313340-18a87480-181e-11ea-91e1-a632d419e3c5.png)

**Comment by xenopeek** [comment]
Using web proxies located in Greece the websites are accessible for me. It may be an issue specific to your ISP. If it doesn't resolve in another day and you have the same issue when connected from other devices, please contact us admins by [email](https://linuxmint.com/contactus.php) as this isn't related to the beta release.

**Comment by clefebvre** [comment]
I think it might have to do with the sucuri change. I'm getting emails from Turkey as well.

**Comment by clefebvre** [comment]
I think this is fixed now. Sucuri introduced a new server, we had to whitelist it, we did so roughly 2 hours ago.

**Comment by jtsagata** [comment]
The issue is fixed for the linuxmint.com.

For the forums there is a security warning about the certificate and then after ignore it a sicuri hosting timeout. Testing by 3 people from PC and mobile. However one person reports a success.
