### ISSUE TITLE
muffin: Fullscreen app window is not centered.

### ISSUE THREAD

**Issue by MichalKolesinski** [linuxmint/mint19.3-beta#2]
![app](https://user-images.githubusercontent.com/39199872/70087534-cd6f4580-1614-11ea-9215-e069a5b62381.png)

This issue is also present in Cinnamon version of Linux Mint 19.2, it wasn't present in 19.1 and before. Problem exist with both Nvidia and Intel graphic card.

My system info:
[code]
System:    Host: CMENTARZ Kernel: 5.0.0-32-generic x86_64 bits: 64 compiler: gcc v: 7.4.0 
           Desktop: Cinnamon 4.4.2 wm: muffin dm: LightDM Distro: Linux Mint 19.3 Tricia 
           base: Ubuntu 18.04 bionic 
Machine:   Type: Laptop System: ASUSTeK product: N53SN v: 1.0 serial: <filter> 
           Mobo: ASUSTeK model: N53SN v: 1.0 serial: <filter> BIOS: American Megatrends 
           v: N53SN.206 date: 04/07/2011 
CPU:       Topology: Quad Core model: Intel Core i7-2630QM bits: 64 type: MT MCP 
           arch: Sandy Bridge rev: 7 L2 cache: 6144 KiB 
           flags: lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 31928 
           Speed: 1428 MHz min/max: 800/2900 MHz Core speeds (MHz): 1: 1312 2: 1293 3: 989 4: 975 
           5: 1389 6: 2010 7: 1675 8: 1226 
Graphics:  Device-1: Intel 2nd Generation Core Processor Family Integrated Graphics 
           vendor: ASUSTeK driver: i915 v: kernel bus ID: 00:02.0 chip ID: 8086:0116 
           Device-2: NVIDIA GF108M [GeForce GT 550M] vendor: ASUSTeK driver: nvidia v: 390.116 
           bus ID: 01:00.0 chip ID: 10de:0df6 
           Display: x11 server: X.Org 1.20.4 driver: modesetting,nvidia 
           unloaded: fbdev,nouveau,vesa compositor: muffin resolution: 1366x768~60Hz 
           OpenGL: renderer: GeForce GT 550M/PCIe/SSE2 v: 4.6.0 NVIDIA 390.116 direct render: Yes 
Audio:     Device-1: Intel 6 Series/C200 Series Family High Definition Audio vendor: ASUSTeK 
           driver: snd_hda_intel v: kernel bus ID: 00:1b.0 chip ID: 8086:1c20 
           Device-2: NVIDIA GF108 High Definition Audio driver: snd_hda_intel v: kernel 
           bus ID: 01:00.1 chip ID: 10de:0bea 
           Sound Server: ALSA v: k5.0.0-32-generic 
Network:   Device-1: Qualcomm Atheros AR9285 Wireless Network Adapter 
           vendor: AzureWave AW-NB037H 802.11bgn driver: ath9k v: kernel port: d000 
           bus ID: 03:00.0 chip ID: 168c:002b 
           IF: wlp3s0 state: down mac: <filter> 
           Device-2: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet 
           vendor: ASUSTeK U6V/U31J laptop driver: r8169 v: kernel port: 9000 bus ID: 05:00.0 
           chip ID: 10ec:8168 
           IF: enp5s0 state: down mac: <filter> 
           Device-3: Atheros AR3011 Bluetooth type: USB driver: btusb bus ID: 1-1.1:3 
           chip ID: 0cf3:3005 
           IF-ID-1: enp0s29u1u2c4i2 state: up speed: N/A duplex: N/A mac: <filter> 
Drives:    Local Storage: total: 465.76 GiB used: 150.61 GiB (32.3%) 
           ID-1: /dev/sda vendor: Seagate model: ST500LM012 HN-M500MBB size: 465.76 GiB 
           speed: 3.0 Gb/s serial: <filter> 
Partition: ID-1: / size: 27.38 GiB used: 8.50 GiB (31.1%) fs: ext4 dev: /dev/sda3 
USB:       Hub: 1-0:1 info: Full speed (or root) Hub ports: 2 rev: 2.0 chip ID: 1d6b:0002 
           Hub: 1-1:2 info: Intel Integrated Rate Matching Hub ports: 6 rev: 2.0 
           chip ID: 8087:0024 
           Device-1: 1-1.1:3 info: Atheros AR3011 Bluetooth type: Bluetooth driver: btusb rev: 1.1 
           chip ID: 0cf3:3005 
           Device-2: 1-1.2:4 info: IMC Networks 2M Integrated Webcam type: Video driver: uvcvideo 
           rev: 2.0 chip ID: 13d3:5122 
           Hub: 2-0:1 info: Full speed (or root) Hub ports: 2 rev: 2.0 chip ID: 1d6b:0002 
           Hub: 2-1:2 info: Intel Integrated Rate Matching Hub ports: 6 rev: 2.0 
           chip ID: 8087:0024 
           Device-3: 2-1.2:3 info: Apple iPhone5/5C/5S/6 type: Still Imaging driver: ipheth,usbfs 
           rev: 2.0 chip ID: 05ac:12a8 
           Hub: 3-0:1 info: Full speed (or root) Hub ports: 1 rev: 2.0 chip ID: 1d6b:0002 
           Device-4: 3-1:2 info: Logitech M105 Optical Mouse type: Mouse 
           driver: hid-generic,usbhid rev: 2.0 chip ID: 046d:c077 
           Hub: 4-0:1 info: Full speed (or root) Hub ports: 1 rev: 3.0 chip ID: 1d6b:0003 
Sensors:   System Temperatures: cpu: 57.0 C mobo: N/A gpu: nvidia temp: 42 C 
           Fan Speeds (RPM): cpu: 2200 
Repos:     No active apt repos in: /etc/apt/sources.list 
           Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list 
           1: deb http: //ftp.acc.umu.se/mirror/linuxmint.com/packages tricia main upstream import backport
           2: deb http: //ftp.acc.umu.se/ubuntu bionic main restricted universe multiverse
           3: deb http: //ftp.acc.umu.se/ubuntu bionic-updates main restricted universe multiverse
           4: deb http: //ftp.acc.umu.se/ubuntu bionic-backports main restricted universe multiverse
           5: deb http: //security.ubuntu.com/ubuntu/ bionic-security main restricted universe multiverse
           6: deb http: //archive.canonical.com/ubuntu/ bionic partner
Info:      Processes: 265 Uptime: 48m Memory: 5.73 GiB used: 1.51 GiB (26.4%) Init: systemd v: 237 
           runlevel: 5 Compilers: gcc: 7.4.0 alt: 7 Client: Unknown python3.6 client inxi: 3.0.32 
[/code]

**Comment by smurphos** [comment]
Existing issue - https://github.com/linuxmint/muffin/issues/530

**Comment by clefebvre** [comment]
We'll tackle this during the cycle and as an update.
