### ISSUE TITLE
Translation Bug German - Cinnamon

### ISSUE THREAD

**Issue by jakoblm** [linuxmint/mint19.3-beta#20]
### Linux Mint 19.3 Cinnamon Beta:

One translation bug in German: If I want to remove the mint menu icon with the right mouse button, the message appears “Möchten Sie Menu wirklich antfernen?”
It would have been translated correctly with: “Möchten Sie **das** Men**ü** wirklich **e**ntfernen?”

**Comment by clefebvre** [comment]
Fixed entfernen in Launchpad (pending translation updated). Can't fix "das Menu..", it's not a sentence per se, we're talking about the name of the applet here.. "%s", so the dialog isn't able to conjugate it as a simple noun.
