### ISSUE TITLE
VirtualBox Shared folders aren't mounted

### ISSUE THREAD

**Issue by MenthaSuaveolens** [linuxmint/mint19.3-beta#22]
Running LM19.3 in a virtual machine on a LM18.3 host. In  LM19.2 the folders shared by the hostOS were automatically mounted (after installing the vbox-additions 5.1.28_122592). Sharing the devices (usb, ...) works well. Even if an external disk (usb) is mounted on the host and the usb-port is passed through the guest, the drive gets mounted in LM19.3.

One has to mount the shared folder in a terminal eg. sudo mount -t vboxsf NameSharedFolder ~/shared/  In this way the shared folder can only be accessed for writing if you apply root-properties, which isn't necessary if the drive is automatically mounted. 

Is this due to the usage of kernel5 i.s.o. kernel4?

**Comment by smurphos** [comment]
I can't reproduce this running the beta as a Guest in Vbox 6.0.14.

**Comment by clefebvre** [comment]
This is out of the scope for us. The upstream Oracle version of both Virtualbox and the guest additions are known to work much better than the Ubuntu ones. If issues remain in these versions they should be reported to Oracle directly. Make sure you're using their latest versions and that no Ubuntu virtualbox (guest or host) packages are present.
