### ISSUE TITLE
Ubiquity installation slideshow features non-default software

### ISSUE THREAD

**Issue by smurphos** [linuxmint/mint19.3-beta#27]
Hi,

It might be worth revising some of the pages of the ubiquity installation slideshow to refer to the current default software e.g. The Watch Movies and Videos slide references Media player and VLC rather than Celluloid, and Gimp is mentioned on the Manage Your Photos slide as a recommended picture editor.

**Comment by clefebvre** [comment]
This is fixed post-BETA release. We're featuring both installed and non-installed software, so typically you'll see Celluloid at the top of the list, along with MPV but also VLC. Same thing with Gimp/Inkscape and Drawing.
