### ISSUE TITLE
live: boot menu is hidden

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/mint19.3-beta#29]
Booting the ISO :
During the countdown, we don’t see the GRUB menu and there’s no indication about how to access to this menu (press a key). A new user doesn’t know how to access to the GRUB menu to test the memory, see the configuration (important during an Install-Party)… Could you show the GRUB menu at the beginning of the downcount “Automatic boot in x seconds…” ?

**Comment by clefebvre** [comment]
I'll miss the hiddenmenu.. I thought it looked really cool. Anyway, this is fixed now for the upcoming stable ISOs. We still have the countdown, but the menu is visible from the start.

**Comment by InfoLibre** [comment]
Yes, it was beautiful, but now it's more ergonomic.
Thank you for this improvement.
