### ISSUE TITLE
LightDM autologin doesn't work

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/mint19.3-beta#30]
I made an installation with choosing autologin for the new user.
But at the first boot after the end of the installation, LightDM ask me a password for the user. It shouldn’t.

**Comment by smurphos** [comment]
I can't reproduce this for the Cinnamon beta iso. Auto login worked fine on initial boot after installation.

**Comment by InfoLibre** [comment]
I have this problem with MATE release.

**Comment by clefebvre** [comment]
Are you using home directory encryption? If so, it's normal.. it cannot work in that case.

**Comment by InfoLibre** [comment]
No, no encryption.

**Comment by clefebvre** [comment]
OK I'll test a new MATE install and try to reproduce it. I successfully tested setting autologin post-install and that worked.

**Comment by clefebvre** [comment]
OK so during installation, /target/etc/lightdm/lightdm.conf is successfully created with autologin settings. Upon rebooting the session is opened automatically without issue.

Tested with MATE BETA 64-bit in Virtualbox.

I'll close the issue as we can't reproduce it.
