### ISSUE TITLE
ubiquity: Bad french keyboard is proposed by default

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/mint19.3-beta#31]
During the installation a bad french keyboard is proposed by default
It seems to be fixed (?) : https://bugs.launchpad.net/ubuntu/+source/ubiquity/+bug/1807344

**Comment by clefebvre** [comment]
Thanks @Petrouchka,

You reported this to us in past 19.x release and then upstream to Ubiquity (https://bugs.launchpad.net/ubuntu/+source/ubiquity/+bug/1807344). It was recently committed upstream https://git.launchpad.net/ubuntu/+source/ubiquity/commit/?id=50042935c5ca0777d7deed7d0c364bae1d5d8b56 and we'll pick it up as a fix when rebasing and importing ubiquity submodules for Mint 20.
