### ISSUE TITLE
mintreport: Missing tray icon

### ISSUE THREAD

**Issue by rvbhute** [linuxmint/mint19.3-beta#33]
OS: Linux Mint Xfce 19.3 Beta

The tray icon for mintReport is missing. It is the third icon from left.

![image](https://user-images.githubusercontent.com/202365/70384843-fba1ac00-19ab-11ea-833f-04c1ed630506.png)

Above, I am using ePapirus icon theme. The screenshot below is with the default Mint-Y icon theme.

![image](https://user-images.githubusercontent.com/202365/70384833-c8f7b380-19ab-11ea-9a5d-922e810e8465.png)

**Comment by clefebvre** [comment]
What tooltip do you get on the missing icon?

**Comment by rvbhute** [comment]
There is no tooltip either for the missing icon.

**Comment by clefebvre** [comment]
What reports do you see in the main window?

**Comment by rvbhute** [comment]
The main window (Detected problems) says "No problems were detected".

**Comment by clefebvre** [comment]
Can you kill any process named mintreport-tray? Make sure they're all dead, then in a terminal, run the tray like this:

`/usr/lib/linuxmint/mintreport/tray.py`

Tell me if you see any error in the terminal.

**Comment by clefebvre** [comment]
Ah wait, no need, I can reproduce it.

**Comment by clefebvre** [comment]
OK it's an issue with the Xfce XAppStatusIcon applet, we'll get that fixed.

**Comment by mtwebster** [comment]
https://github.com/linuxmint/xfce4-xapp-status-plugin/pull/1 fixes.

**Comment by clefebvre** [comment]
Fixed.
