### ISSUE TITLE
Mate / live session - Sound preferences not saved after closing dialog box

### ISSUE THREAD

**Issue by Groberen** [linuxmint/mint19.3-beta#38]
Computer model: Acer Aspire e (A315-53)
Boot:  ISO image (not installed yet) directly from USB stick "linuxmint-19.3-mate-64bit-beta.iso"

ISSUE : Steps to reproduce
* Open "Sound preferences" dialog
* Do some changes - i.e. enable sounds
* Close dialog box.
* Open  "Sound preferences" dialog again.

EXPECTED RESULT
All sound preferences should be as it was at the time when dialog box was closed.

ACTUAL RESULT
All sound preference are reset to "default" - i.e. as when the "Sound preferences" was opened for the very first time.

**Comment by clefebvre** [comment]
Tested with MATE BETA 64-bit. Unable to reproduce the issue.

Settings persist.

Off-topic note: Settings modified in live mode are not supposed to affect post-installation sessions.
