### ISSUE TITLE
System reports says I need to set a root password even after setting root password.

### ISSUE THREAD

**Issue by joshontech** [linuxmint/mint19.3-beta#39]
I clicked on system report applet in the panel and it said I need to set a root password. I do so and reboot and it continues to tell me I need to set root password. The only way to get rid of this is to click "ignore this problem" in the system reports window.

**Comment by clefebvre** [comment]
We'll review this. It's working as designed but the design is obviously confusing :)

Closing it here since it's tracked in trello already.
