### ISSUE TITLE
nemo: Moving item from trash to desktop restores it

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/mint19.3-beta#40]
The problem is described [here on the nemo bugtracker](https://github.com/linuxmint/nemo/issues/1814). The problem persists in the beta.

To reproduce: create folder ~/TEST. Move it to trash. Drag it from trash to desktop.

Frequency: always, it seems.

**Comment by leigh123linux** [comment]
This issue isn't new.

**Comment by LinuxOnTheDesktop** [comment]
No, it is not new, but:

1) the same holds for some things that have been reported and indeed been fixed on this the beta bug tracker;

2) the issue is marked (edit: and has been for a long time, I think) as 'in progress' in the nemo bugtracker;

3) the problem is fairly serious, for it can lead users to think that the OS has permanently and erroneously deleted their materials.

**Comment by leigh123linux** [comment]
It's not something we can fix within nemo.
Trash behaviour is controled by gvfs-trash (part of gvfs), restore data is store in ~/.local/share/Trash/info/

Don't expect gvfs virtual file systems to behave the same as normal directories.

 https://en.wikipedia.org/wiki/GVfs

**Comment by LinuxOnTheDesktop** [comment]
Sorry to bang on, but the average user (i) is going to suppose that dragging something from trash to desktop will work, (ii) will be mystified by what actually happens.

So it seem to me that whatever the causes, the result is a user experience that rather violates Mint's mission of providing an accessible, usable version of Linux.

Also: what then of that 'in progress' label? Does it mean gvfs developers are working on a fix? But, ah, I see your contribution to the Nemo thread . .

**Comment by gm10** [comment]
@leigh123linux well, MATE's caja handles it correctly. Whether that means it's a nemo bug after all or they implement a workaround I cannot say, I didn't look into it.

**Comment by leigh123linux** [comment]
@gm10 Do you have any idea which commit in caja fixes it?

**Comment by gm10** [comment]
@leigh123linux as I said, I didn't look into it. I wasn't even aware of the nemo issue before I saw this issue come up on the beta tracker. For what it's worth, I just checked with Thunar and Nautilus and they also handle this correctly, so this has every indication of being a home-grown bug with nemo.

**Comment by LinuxOnTheDesktop** [comment]
I imagine that Githib's advanced search, employed to search for 'trash' in the commits in the repository mate-desktop/caja would be a place to start. But I don't know, because I can't grasp how one does such a search.

**Comment by leigh123linux** [comment]
I think this describes the issue in nautilus https://bugzilla.gnome.org/show_bug.cgi?id=721981
