### ISSUE TITLE
cinnamon: gwl - too easy to delete one's config

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/mint19.3-beta#42]
Since Grouped Window List has been worked on recently, might I ask that the [#8634](https://github.com/linuxmint/cinnamon/issues/8634) be revisited, even though the problem is not new to the beta (though does persist in it)? 

That report says: it is too easy to accidentally remove the GWL applet. I thought that problem might bite me at one point and just now it did. I think that 'bite' was made more likely by my using a small screen (1366 x 768, non-HiDPI, ThinkPad X230). I hit the wrong button by accident (I was trying to _configure_ GWL), there was no confirmation required, and, bam, my GWL, and all its pinned icons and their ordering, were irrecoverably gone.

**Comment by smurphos** [comment]
Bug confirmed - the confirmation dialog introduced by https://github.com/linuxmint/cinnamon/commit/5e0b03e93b3e2e4e50c7de91e56ac09735dd390d isn't displaying for GWL in 4.4.3 (and 4.2.4).

**Comment by smurphos** [comment]
It also affects the regular window-list applet and the panel-launcher applet - no confirmation dialog is displayed when removing those applets via right click on the panel either.
