### ISSUE TITLE
nemo-extensions are still 4.2

### ISSUE THREAD

**Issue by VaGNaroK** [linuxmint/mint19.3-beta#44]
Choosing folder properties and clicking "share" a blue bar showing that samba should be installed is not translated to pt_BR.

Link for image:

https://postimg.cc/jwn5hXBB

Hardware:
System: Host: vagnarok-PC 
Kernel: 5.0.0-37-generic x86_64 bits: 64 
Desktop: Cinnamon 4.4.4 
Distro: Linux Mint 19.3 Tricia (BETA)

**Comment by clefebvre** [comment]
oh wow... nemo-extensions aren't up to date. Thanks for this!

**Comment by clefebvre** [comment]
OK fixed.
