### ISSUE TITLE
Install fails when 2 mediums available

### ISSUE THREAD

**Issue by tjf6508** [linuxmint/mint19.3-beta#45]
Machine is AMD A8-7600 APU with 8gb ram. Solid machine. 

Attempted install of 19.2 MATE with both NVME SSD and SATA SSD installed. Intended to use the SATA drive as boot disk and NVME as secondary storage.

Attempted install to SATA drive, all proceeded normally until Grub install failed. It appeared to be confused as to where to put the grub boot code and install aborted.

Retried with NVME drive as target, same or similar results, install aborted.

Removed SATA drive, install ran to completion with no errors, new system ran fine from internal NVME.

Removed NVME and reinstalled SATA, install ran to completion and system runs fine. 

Install always seems to be OK with a single drive but aborts at GRUB install if two or more drives available, regardless of which one is target.

**Comment by clefebvre** [comment]
Thanks @tjf6508, 

This is upstream from us but we can chase it up and see if it's fixed. We'll need exact partition names, screenshots and error messages to fully understand the issue here though.

**Comment by tjf6508** [comment]
I can't produce that information any more, I've started using the hardware
for another project. Sorry.

**Comment by clefebvre** [comment]
thanks @tjf6508, that's ok.
