### ISSUE TITLE
ufraw-batch Segmentation fault

### ISSUE THREAD

**Issue by brunomgalmeida** [linuxmint/mint19.3-beta#46]
ufraw 0.22-3.1~build0.18.04.1 abruptly fails with `Segmentation fault`. 

```sh
XXXX@server:~/Downloads$ ufraw-batch --wb=camera --out-type=jpg *.RW2
ufraw-batch: Loaded P1130572.RW2 [1/23]
ufraw-batch: Saved /home/XXXX/Downloads/PXXXX2.jpg [1/23]
Segmentation fault (core dumped)
```

To fix I installed the latest ufraw version 0.22-4.1

http://archive.ubuntu.com/ubuntu/pool/universe/u/ufraw/ufraw-batch_0.22-4_amd64.deb
http://archive.ubuntu.com/ubuntu/pool/universe/u/ufraw/ufraw_0.22-4_amd64.deb

**Comment by xenopeek** [comment]
Bug report for the same in Ubuntu LTS 18.04: https://bugs.launchpad.net/ubuntu/+source/ufraw/+bug/1768855. As noted there in comment 21 this won't be fixed in the repository and is removed from repositories after 19.04. Workaround is your fix or switching to a different program.
