### ISSUE TITLE
Added Cinnamon desktop to MATE distro, no joy

### ISSUE THREAD

**Issue by tjf6508** [linuxmint/mint19.3-beta#47]
I am using the MATE distro and have found it to work well. However I'm more accustomed to using Cinnamon desktop so, using the software manager, I installed it. Logged out, logged back in selecting cinnamon instead of MATE.

Desktop came up and was working until I tried opening the system settings to make some changes. Nothing in there would work. And by not working I mean that when I click on the icon the apps fail to open. Nothing happens. 

I haven't tried the native Cinnamon distro, can only assume it works, but when I simply add Cinnamon desktop to MATE distro no joy.

I did try rebooting, and I tried uninstall/reinstall. Nothing.

So I'm assuming that you guys would like to know about this before 19.3 goes live.

**Comment by smurphos** [comment]
What exactly did you install?

'apt install mint-meta-cinnamon' should bring in everything needed .

**Comment by tjf6508** [comment]
I just used the software install app from the GUI menu. I really feel like
that ought to work and not have to resort to apt.

**Comment by tjf6508** [comment]
FYI I went back and installed Cinnamon using "apt install mint-meta-cinnamon" and it works fine. 
However I feel like you will have a lot fewer frustrated users if you make the software manager installs work properly first time.

**Comment by smurphos** [comment]
There's lots of Cinnamon related packages in Software manager - it would be helpful to know which exactly you selected to install originally

![screenshot-screen-2019-12-11-053037](https://user-images.githubusercontent.com/29017677/70594282-e741f700-1bd7-11ea-9862-30d678d79609.png)

**Comment by tjf6508** [comment]
The first one in your list, "Modern Linux Desktop" is what I installed
originally.

With so many choices it would be helpful to have some guidance as to which
packages are necessary, obviously I picked the wrong one even though its
description seemed the most obvious.

**Comment by clefebvre** [comment]
Added to the roadmap for consideration. Closing here as it's not a release breaker.

**Comment by clefebvre** [comment]
Sorry, I forgot to answer @tjf6508 , I'd say `cinnamon-desktop-environment` would be the best candidate.

**Comment by clefebvre** [comment]
The `cinnamon` package itself is just cinnamon itself, from a technical point of view.. i.e. the panel, applets, window manager... and that's it, no settings daemon, no session manager etc..

**Comment by tjf6508** [comment]
If you want to reduce confusion and reduce trouble reports in the release
version, the one at the top of the list should be labelled "This is the
complete package" and it should include everything that's needed.
