### ISSUE TITLE
Disappearing Logo on startup - reproducible

### ISSUE THREAD

**Issue by smgordon1207** [linuxmint/mint19.3-beta#48]
I noticed that the Start up logo had stopped showing up so I been playing around to figure out why. 
It disappears each time I install any one of the available nvidia graphics drivers (435,430,390,340). works just fine using the xserver drivers ( open source). Reinstalled 19.3 each time I installed a new driver to eliminate residual  crud left in the system. Another weird side effect was that the system report icon was not showing up in the panel. all is working fine with xserver for now.

ASUS M5A78L-M/USB3 /AMD FX-4350 (4.2gHz) / Vulcan DDR3 1600MHz 8Gb
EVGA GTX 660 2Gb / xserver / Element 32" 1080p
Linux Mint 19.3b MATE amd64 / Kernel 5.3.0-24 generic x86_64
Primary: PNY 120Gb SSD Secondary: Seagate 1Tb SSHD

**Comment by clefebvre** [comment]
Hi @smgordon1207, 

There's not much we can do about this. We can't modify/troubleshoot proprietary drivers. There are workarounds on the web to make plymouth (which runs the boot splash logo) work with NVIDIA drivers though.

I'll close this here as it won't lead to a fix.

**Comment by smgordon1207** [comment]
Thank you, sending information to nvidia
