### ISSUE TITLE
Virtualbox: Blackscreen when booting the Cinnamon or Mate ISO when using VboxVGA or VboxSVGA

### ISSUE THREAD

**Issue by Hanouta** [linuxmint/mint19.3-beta#49]
When trying to boot the Cinnamon or Mate ISO I get a blackscreen when using the VboxVGA or VboxSVGA graphics controller. I didn't have this issue when using the Xfce ISO. Booting in compatibility mode can be used as a workaround.

**Comment by smurphos** [comment]
VMSVGA is intended for Linux Guests.

**Comment by clefebvre** [comment]
It's a regression since we applied the Kernel 5.0 and HWE Xorg. It's on Virtualbox though, there's not much we can do. Also, experience may vary, we have it happening here with the Xfce ISO.

The release notes were edited to describe that.

**Comment by gm10** [comment]
@clefebvre it's not on VirtualBox. The default graphics controller for Linux guests is VMSVGA, and the documentation explains that VboxSVGA is for Win7+ and VboxVGA for older Windows guests. So this is a case of incorrectly changing the default configuration without having read the manual, nothing more.
