### ISSUE TITLE
19.3 beta Cinnamon Panel font size

### ISSUE THREAD

**Issue by jtcraigjr** [linuxmint/mint19.3-beta#50]
Please consider that those of us who are using newer hardware with 17" screens, and 4k HiDef resolution are experiencing a LOT of trouble making the Fonts in the Panel large enough.
I would appreciate raising the limit to 16 points.
I am 78, color blind, and even with 12 pt fonts, I have a lot of trouble reading the fonts and easily determining what those little dinky icons are.

Thank you
John Craig

**Comment by leigh123linux** [comment]
Have you tried using the font scaling option in cinnamon-settings fonts?
