### ISSUE TITLE
Odd install option when clean installing over 19.2

### ISSUE THREAD

**Issue by netjerykhet** [linuxmint/mint19.3-beta#51]
When performing a clean install of 19.3 Cinnamon BETA over the top of 19.2, an option is presented to the user to reinstall 19.2. This is unexpected behaviour and possibly highly confusing.

![Screenshot from 2019-12-11 03-59-37](https://user-images.githubusercontent.com/3529932/70690528-f2e20a80-1d0a-11ea-9f38-171d6ab95351.jpg)

**Comment by clefebvre** [comment]
It's slightly confusing because it's more or less the same between option 1 and 3. We'll check again in Mint 20 with the upgraded partman submodule.

The label is OK though, you're erasing 19.2 and reinstalling... it implicitly mean reinstalling the distro, not the 19.2 version.
