### ISSUE TITLE
cinnamon: pinned apps do not appear in other workspaces

### ISSUE THREAD

**Issue by Pakatonobr** [linuxmint/mint19.3-beta#53]
- Linux Mint 19.2 Cinnamon
- Cinnamon 4.2.4

Disclaimer:
This bug is apparently arbitrary, in some workspaces applications appear and in others not.

To reproduce:
1. Pin random app on the panel, preferably 3 apps to see the error more clearly;
2. Switch to other workspaces and you will see that these applications were not pinned to these workspaces' panels.

Example:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/37935420/70717702-a926ff00-1ccd-11ea-9ddd-f6c24961ec37.gif)

**Comment by mtwebster** [comment]
Fixed in 4.4.3:
https://github.com/linuxmint/cinnamon/commit/7fcdcbee64fb65a530c5dc61ed427c1ec301f497#diff-10f95e2348d1571d611014de1fa17308
