### ISSUE TITLE
Can't import openvpn config from .ovpn file.

### ISSUE THREAD

**Issue by freakout555** [linuxmint/mint19.3-beta#54]
When I try to import an .ovpn file I get the following error:

The file "*.ovpn" could not be read or does not contain recognized VPN connection information.
Error: the plugin does not support import capability.

I'm using the official PIA .ovpn config files.

I have attached a screenshot of the error.
![ovpn-error](https://user-images.githubusercontent.com/58820807/70727481-6d5d5b00-1d08-11ea-9088-c13440d6eefa.png)

**Comment by clefebvre** [comment]
Thanks @freakout555 

This is upstream from us. It can happen if there's anything wrong in the the file itself.. the error message isn't very useful unfortunately..

Check https://askubuntu.com/questions/761684/error-the-plugin-does-not-support-import-capability-when-attempting-to-import for more info on this.
