### ISSUE TITLE
firefox: mint branding incomplete?

### ISSUE THREAD

**Issue by MrEen-Mint** [linuxmint/mint19.3-beta#55]
I don't use Firefox much anymore and just noticed the bookmarks toolbar Mint entries (Linux Mint, Blog, Forums, Community) are not there anymore.

Also, there's a menu entry in Bookmarks "Ubuntu and Free Software links" containing Ubuntu and Debian links that might be unwanted. Image link below:

https://mreen.000webhostapp.com/ffbranding.png

**Comment by clefebvre** [comment]
We no longer put Mint bookmarks since the menubar isn't visible by default anymore. The bookmarks from Ubuntu are removed since 71.0.
