### ISSUE TITLE
cinnamon: Screensaver freezes

### ISSUE THREAD

**Issue by MichalKolesinski** [linuxmint/mint19.3-beta#6]
When I lock the screen myself, all is working perfect, while trying to unlock it. Unfortunately, when screen locks after computer is not being used, the screen is totally unresponsive. I'm not able to use the virtual keyboard, or see the password signs. Login is possible though. Only the graphical side "freezes".

**Comment by mtwebster** [comment]
Can you go into your Power settings, and disable the 'Turn off the screen when inactive for' (if it's enabled at all) - and then allow the computer to idle again to see if this recurs.

Thanks

**Comment by MichalKolesinski** [comment]
I turned it off. As long as screen is "on", there's no problem. But I have also manually turned off the screen, and then, after turning on it freezes again.

**Comment by clefebvre** [comment]
> Only the graphical side "freezes".

So when you move the mouse or start typing... you can see the screensaver and its input password field... but the characters in it don't show up.. and everything's fine again after you press Enter?

**Comment by clefebvre** [comment]
I remember we had this issue in 19.2 already. I could reproduce it easily with a laptop connected to a TV with HDMI:

- connect to HDMI
- lock screen
- remove HDMI cable
- unlock session

I think it's triggered by display changes. Here on the OP's computer it's probably the screen turning itself off completely.

**Comment by MichalKolesinski** [comment]
That’s the problem I have. As you mentioned, I can unlock the computer, but I can’t see the input. It would not be a big deal, but it also renders the virtual keyboard useless. Maybe 99% of times one does not use it, but this 1% when a button stops to work and you can’t unlock your device may happen one day :D

**Comment by mtwebster** [comment]
Could I get you to try the packages I've mentioned here: https://github.com/linuxmint/muffin/issues/530#issuecomment-563476189

And see if you still have this issue?  Thanks

**Comment by clefebvre** [comment]
We'll tackle this as an update post-release.
