### ISSUE TITLE
mintdrivers: false positive for missing drivers running in virtualbox

### ISSUE THREAD

**Issue by smurphos** [linuxmint/mint19.3-beta#8]
Hi,

Running 19.3 Cinnamon beta in Virtualbox 6.0.x with Guest Additions installed via the Vbox interface and using the VMSVGA graphics controller, mintreport warns of missing drivers.

![Screenshot from 2019-12-04 04-18-55](https://user-images.githubusercontent.com/29017677/70112468-5bffb900-164d-11ea-9452-cba716e197c6.png)

Driver Manager incorrectly reports that both the Graphics Driver and Guest Additions are not working. Even if the user takes that info at face value, the solutions suggested by Driver manager can't be implemented from it's interface.

![Screenshot from 2019-12-04 04-18-18](https://user-images.githubusercontent.com/29017677/70112506-7d60a500-164d-11ea-855d-6ddf6813a3d9.png)

Inxi -Gxxxz
```
Graphics:
  Device-1: VMware SVGA II Adapter driver: vmwgfx v: 2.15.0.0 
  bus ID: 00:02.0 chip ID: 15ad:0405 
  Display: x11 server: X.Org 1.20.4 driver: vmware 
  unloaded: fbdev,modesetting,vesa resolution: 1920x1080~60Hz 
  OpenGL: renderer: SVGA3D; build v: 2.1 Mesa 19.0.8 direct render: Y
```

Re the suggested packages - it's really not a good idea to use the repo version of Guest Additions when the host Virtualbox is not the same repo version.  

I'm not clear if the open-vm-tools-desktop package actually has any utility in a Virtualbox installation. It appears to provide broadly equivalent functions to Guest Additions if installed in a guest OS that is actually running on Vmware.

**Comment by clefebvre** [comment]
Fixed in mintdrivers 1.4.4 and mintreport 1.1.2.
