### ISSUE TITLE
cinnamon: Panel font sizes need more options due to hidpi

### ISSUE THREAD

**Issue by mtwebster** [linuxmint/mint19.3-beta#9]
Double them? 6-12 to 12-24

**Comment by smurphos** [comment]
Personally I'd get rid of the fractional options and do 8 to 16 as the standard options.

With nothing specific set by the theme it would default to 10pt, it any case. I think 6pt would be too small in any case on any supported screen resolution. 8pt - 10pt is OK on 1366 x 768. 11pt - 12pt looks good on 1920 x 1080. 

I suspect that options > 12pt are needed for resolutions greater than 1920 x 1080 that don't meet the threshold for auto HIDPI.

**Comment by JosephMcc** [comment]
I'm a bit confused by this one. It doesn't seem to work any different for me under HiDPI. Aren't they being scaled just like everything else? Selecting 12 in the dropdown gives me a really large font.

**Comment by mtwebster** [comment]
You're right I'm an idiot - I have a ssecondary 4k monitor I use in normal dpi.  I bump the panel size up on it to increase visibility, I confused myself thinking this was why the text was so small.  I wasn't actually in hidpi mode..
